# Generated by Django 5.0.4 on 2024-04-30 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Критерий ранжирования',
                'verbose_name_plural': 'Критерии ранжирования',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(verbose_name='Создан')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='Результаты')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_incidents', to='incidents.expert', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
        migrations.CreateModel(
            name='IncidentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.criteria', verbose_name='Критерий')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент')),
            ],
            options={
                'verbose_name': 'Критерий ранжирования инцидента',
                'verbose_name_plural': 'Критерии ранжирования инцидента',
                'unique_together': {('incident', 'criteria')},
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='criteries',
            field=models.ManyToManyField(through='incidents.IncidentCriteria', to='incidents.criteria'),
        ),
        migrations.CreateModel(
            name='IncidentExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('scores', models.JSONField(blank=True, null=True, verbose_name='Оценки')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.expert', verbose_name='Эксперт')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент')),
            ],
            options={
                'verbose_name': 'Эксперт по инциденту',
                'verbose_name_plural': 'Эксперты по инциденту',
                'unique_together': {('incident', 'expert')},
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='experts',
            field=models.ManyToManyField(through='incidents.IncidentExpert', to='incidents.expert'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.status', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент')),
            ],
            options={
                'verbose_name': 'Базис инцидента',
                'verbose_name_plural': 'Базисы инцидента',
                'unique_together': {('incident', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент')),
            ],
            options={
                'verbose_name': 'Стратегия устранения инцидента',
                'verbose_name_plural': 'Стратегии устранения инцидента',
                'unique_together': {('incident', 'name')},
            },
        ),
    ]
