# Generated by Django 5.0.4 on 2024-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_results_alter_incidentexpert_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_solution',
            field=models.BooleanField(default=False, verbose_name='Является решением'),
        ),
    ]
