# Generated by Django 5.0.4 on 2024-04-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critery',
            options={'verbose_name': 'Критерий ранжирования', 'verbose_name_plural': 'Критерии ранжирования'},
        ),
        migrations.AlterModelOptions(
            name='incidentbasis',
            options={'verbose_name': 'Базис инцидента', 'verbose_name_plural': 'Базисы инцидента'},
        ),
        migrations.AlterModelOptions(
            name='incidentcritery',
            options={'verbose_name': 'Критерий ранжирования инцидента', 'verbose_name_plural': 'Критерии ранжирования инцидента'},
        ),
        migrations.AlterModelOptions(
            name='incidentexpert',
            options={'verbose_name': 'Эксперт по инциденту', 'verbose_name_plural': 'Эксперты по инциденту'},
        ),
        migrations.AlterModelOptions(
            name='incidentstrategy',
            options={'verbose_name': 'Стратегия устранения инцидента', 'verbose_name_plural': 'Стратегии устранения инцидента'},
        ),
        migrations.AlterField(
            model_name='incidentbasis',
            name='basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.basis', verbose_name='Базис'),
        ),
        migrations.AlterField(
            model_name='incidentbasis',
            name='basis_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='incidentbasis',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент'),
        ),
        migrations.AlterField(
            model_name='incidentcritery',
            name='critery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.critery', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='incidentcritery',
            name='critery_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='incidentcritery',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент'),
        ),
        migrations.AlterField(
            model_name='incidentexpert',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.expert', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='incidentexpert',
            name='expert_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='incidentexpert',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент'),
        ),
        migrations.AlterField(
            model_name='incidentstrategy',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident', verbose_name='Инцидент'),
        ),
        migrations.AlterField(
            model_name='incidentstrategy',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.strategy', verbose_name='Стратегия'),
        ),
        migrations.AlterField(
            model_name='incidentstrategy',
            name='strategy_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер'),
        ),
    ]
