# Generated by Django 5.0.4 on 2024-04-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentexpert_scores_alter_expert_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='name',
            field=models.CharField(default='Тест', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basis',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
