# Generated by Django 5.0.4 on 2024-04-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_basis_name_alter_basis_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
