# Generated by Django 5.0.4 on 2024-04-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_rename_creator_id_incident_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidentexpert',
            unique_together={('incident', 'expert')},
        ),
    ]
