# Generated by Django 5.0.4 on 2024-04-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_alter_incidentexpert_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidentbasis',
            unique_together={('incident', 'basis')},
        ),
        migrations.AlterUniqueTogether(
            name='incidentcritery',
            unique_together={('incident', 'critery')},
        ),
        migrations.AlterUniqueTogether(
            name='incidentstrategy',
            unique_together={('incident', 'strategy')},
        ),
    ]
